const STORAGE_KEY = 'asapConversationCounterV1';
const categories = ['meatEater','vegetarian','vegan','receptive','committed'];
const dietKeys = new Set(['meatEater','vegetarian','vegan']);
const labels = { meatEater:'Meat Eater', vegetarian:'Vegetarian', vegan:'Vegan', receptive:'Receptive', committed:'Committed to Go Vegan' };

function freshState(){ return { counts:{meatEater:0,vegetarian:0,vegan:0,receptive:0,committed:0}, history:[], campus:'', person:'' }; }
function load(){ try { return {...freshState(), ...JSON.parse(localStorage.getItem(STORAGE_KEY) || '{}')}; } catch { return freshState(); } }
let state = load();

function save(){ localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); }

function total(){
  return state.counts.meatEater
    + state.counts.vegetarian
    + state.counts.vegan
    + state.counts.receptive
    + state.counts.committed;

}

function render(){
  categories.forEach(k => document.getElementById(k+'Count').textContent = state.counts[k] || 0);
  document.getElementById('totalCount').textContent = total();
  document.getElementById('campusInput').value = state.campus || '';
  document.getElementById('personInput').value = state.person || '';
  document.getElementById('undoBtn').disabled = state.history.length === 0;
}
function tap(key){
  state.counts[key] = (state.counts[key] || 0) + 1;
  state.history.push({key, at:new Date().toISOString()});
  save(); render();
  if (navigator.vibrate) navigator.vibrate(20);
}

document.querySelectorAll('.counter').forEach(btn => btn.addEventListener('click', () => tap(btn.dataset.key)));
document.getElementById('undoBtn').addEventListener('click', () => {
  const last = state.history.pop(); if (!last) return;
  state.counts[last.key] = Math.max(0, (state.counts[last.key] || 0) - 1); save(); render();
});
document.getElementById('resetBtn').addEventListener('click', () => {
  if (!confirm('Reset all counts and tap history?')) return;
  const campus = state.campus, person = state.person; state = freshState(); state.campus=campus; state.person=person; save(); render();
});
['campusInput','personInput'].forEach(id => document.getElementById(id).addEventListener('input', e => {
  state[id === 'campusInput' ? 'campus' : 'person'] = e.target.value; save();
}));

document.getElementById('dateLabel').textContent =
  new Date().toLocaleDateString(undefined, {
    weekday: 'long',
    month: 'long',
    day: 'numeric'
  });

// AUTO-FILL DATE WITH TODAY
const dateInput = document.getElementById('dateInput');

if (dateInput && !dateInput.value) {
  const today = new Date();

  const year = today.getFullYear();
  const month = String(today.getMonth() + 1).padStart(2, '0');
  const day = String(today.getDate()).padStart(2, '0');

  dateInput.value = `${year}-${month}-${day}`;
}

render();

// EMAIL RESULTS
const emailBtn = document.getElementById('emailBtn');

emailBtn.addEventListener('click', () => {

  const emailInput = document.getElementById('emailInput');
  const email = emailInput.value.trim();

  if (!email) {
    alert('Please enter an email address.');
    emailInput.focus();
    return;
  }

  if (!emailInput.checkValidity()) {
    alert('Please enter a valid email address.');
    emailInput.focus();
    return;
  }

  // USE SELECTED DATE
  const dateInput = document.getElementById('dateInput');

  let date;

  if (dateInput && dateInput.value) {
    const selectedDate = new Date(dateInput.value + 'T12:00:00');
    date = selectedDate.toLocaleDateString();
  } else {
    date = new Date().toLocaleDateString();
  }

  const subject =
    `ASAP Outreach Results - ${date}` +
    (state.campus ? ` - ${state.campus}` : '');

  const body = [
    'ASAP OUTREACH RESULTS',
    '',
    `Date: ${date}`,
    `Campus: ${state.campus || 'Not entered'}`,
    `Location: ${state.person || 'Not entered'}`,
    '',
    `TOTAL CONVERSATIONS: ${total()}`,
    '',
    `Meat Eater: ${state.counts.meatEater || 0}`,
    `Vegetarian: ${state.counts.vegetarian || 0}`,
    `Vegan: ${state.counts.vegan || 0}`,
    `Receptive: ${state.counts.receptive || 0}`,
    `Committed to Go Vegan: ${state.counts.committed || 0}`,
    '',
    '-------------------------',
    'Generated by ASAP Conversation Counter'
  ].join('\n');

  // Detect iPhone / iPad
  const isIOS =
    /iPad|iPhone|iPod/.test(navigator.userAgent) ||
    (navigator.platform === 'MacIntel' && navigator.maxTouchPoints > 1);

  if (isIOS) {

    // iPhone/iPad: use the device's configured email app
    const mailto =
      `mailto:${email}` +
      `?subject=${encodeURIComponent(subject)}` +
      `&body=${encodeURIComponent(body)}`;

    window.location.href = mailto;

  } else {

    // Desktop: open Gmail compose
    const gmailURL =
      'https://mail.google.com/mail/?view=cm&fs=1' +
      `&to=${encodeURIComponent(email)}` +
      `&su=${encodeURIComponent(subject)}` +
      `&body=${encodeURIComponent(body)}`;

    window.open(gmailURL, '_blank');
  }
});
